### ISSUE TITLE
Install errors out while cloning Swift Argument Parser

### ISSUE THREAD

**Issue by conath** [hannesoid/AppIconAssigner#1]
I ran 
```terminal
git clone https://github.com/hannesoid/AppIconAssigner
cd AppIconAssigner
make install
```

This was the output:

```terminal
swift build -c release
Fetching git@github.com:apple/swift-argument-parser.git
error: Failed to clone git@github.com:apple/swift-argument-parser.git:
    Cloning into bare repository '/Users/chris/Documents/AppIconAssigner/.build/repositories/swift-argument-parser-dcbbf3c8'...
    Host key verification failed.
fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.
```

**Comment by conath** [comment]
I fixed it on my machine with [these changes](https://github.com/conath/AppIconAssigner/pull/1).

**Comment by hannesoid** [comment]
Cool thanks!
I'm not fully sure when best to use SSH (git@…) over HTTPS for package dependencies, but for me resolving also works for the https variant, so looks good, would merge your changes. 

Your PR currently points to your own fork, could you make one pointing to this?
While you're at it, can you also add package.resolved to the .gitignore so it doesn't come back?

**Comment by conath** [comment]
Ok, I created #2
